### ISSUE TITLE
Cannot connect to backend

### ISSUE THREAD

**Issue by joal2** [asikart/remoteimage#18]
I just installed Asikart RemoteImage.  I love it but ran into a problem.  When I edit a picture and save - I get the error message in the subject line.

Dee Hanak
joal222@yahoo.com

**Comment by asika32764** [comment]
It's weird, I can't reproduce this issue in Joomla 3.3.6.

Is this issue still exists for you?

**Comment by asika32764** [comment]
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)
