### ISSUE TITLE
Invalid jQuery UI configuration.

### ISSUE THREAD

**Issue by winini** [asikart/remoteimage#24]
Hello,
The component worked well since installation (and used in admin), but now I have this jquery error :
"Invalid jQuery UI configuration. Selectable, draggable and droppable components must be included".

I do not know exactly when? Maybe since the update joomla 3.3.3.
in admin of my site, I do not have any settings or plugins to choose options jquery.
Can you please guide me.

Thanks.

**Comment by asika32764** [comment]
Issue close since it has been resolved.
