### ISSUE TITLE
Invalid backend configuration. Readable volumes not available.

### ISSUE THREAD

**Issue by joris85** [asikart/remoteimage#25]
Hello,

I get this error after installation.
I go to the component and see this
--- Invalid backend configuration.
Readable volumes not available.---

I checked the image folder chmod and settings.
Do not see why this is happening.

I have the idea it is my hosting provider rights problem.
But what can i ask them to change if it is?

Thanks!

Here the error image:
![screen shot 2014-09-19 at 12 43 28](https://cloud.githubusercontent.com/assets/5088751/4334135/da2e066e-3fe9-11e4-922f-844a7de6fe87.png)

**Comment by asika32764** [comment]
Sorry for lately reply.

Is there any update of this issue?

**Comment by enofdevelop** [comment]
Hey!

I have the same problem.
Did you find a solution?

greetings

**Comment by joris85** [comment]
Hello,
Well i think this was because i did not set the location of the image folder.
I now use it on a couple sites without this problem.
But i am not sure about this because its a while ago :-)

**Comment by asika32764** [comment]
There is no update of this issue, closed
