### ISSUE TITLE
Check For Updates Error

### ISSUE THREAD

**Issue by designsubway** [asikart/remoteimage#27]
When I use the Joomla extension manager to check for updates to extensions I get the error:
> Update: :Extension: Could not parse https://raw.githubusercontent.com/asikart/remoteimage/staging/update.xml

**Comment by asika32764** [comment]
I think this error have been fix in https://github.com/asikart/remoteimage/pull/35

I'll test this soon.

**Comment by asika32764** [comment]
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)
