### ISSUE TITLE
conflict with administrator folder pass

### ISSUE THREAD

**Issue by farhadst** [asikart/remoteimage#30]
hi
i have pass on administrator folder
1.install remoteimage
2.now on all frontend page need pass
3.but when disable only "Remoteimage Redirect plugin" problem resolved

**Comment by asika32764** [comment]
Remoteimage will only redirect com_media component.

Could you try Remoteimage on a new pure Joomla to check that if it caused by plugin confliction of not? 

That I can determine the reason.

**Comment by asika32764** [comment]
Issue no updated, closed.
