### ISSUE TITLE
Resizing dialogue not showing

### ISSUE THREAD

**Issue by bobr666** [asikart/remoteimage#32]
I am trying to get RemoteImage working - it looks much better than the standard image manager. One problem I am having is that when I select the "Resize" dialogue, I can't get past the "loading image" message. Any ideas?

**Comment by asika32764** [comment]
I think it is a known issue in 2.0.1, see: https://github.com/asikart/remoteimage/issues/22

W'll fix this in next release.

**Comment by asika32764** [comment]
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)
