### ISSUE TITLE
Missing path to JS-file '/includes/js/remoteimage-admin.js'

### ISSUE THREAD

**Issue by shkodskihk** [asikart/remoteimage#33]
Missing path to JS-file: /components/com_remoteimage/includes/js/remoteimage-admin.js
- version: 2.0.1
- in file: \plugins\editors-xtd\remoteimage\remoteimage.php
- at line: 67
- code:
$doc->addScript(JURI::root(true) . '/components/com_remoteimage/includes/js/remoteimage-admin.js');

**Comment by asika32764** [comment]
Fixed
