### ISSUE TITLE
Error in Joomla 3.4beta3

### ISSUE THREAD

**Issue by Gerlof** [asikart/remoteimage#38]
I installed RemoteImage using the option [Install from Web]. During installation, no errors were reported.

In Administrator, selecting Components > RemoteImage results in this error message:
An error has occurred. - 500 Library path /libraries/framework cannot be found

**Comment by asika32764** [comment]
Joomla 3.4 removed this folder, please add it before we fix this bug.

See: https://github.com/joomla/joomla-cms/tree/staging/libraries

**Comment by asika32764** [comment]
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)

**Comment by Gerlof** [comment]
Thanks for the update!
