### ISSUE TITLE
Installation seems ok but component doesn't work

### ISSUE THREAD

**Issue by nono33** [asikart/remoteimage#39]
This extension is exactly what I need on my production site. So, to test it, I've installed remoteimage on my local xampp site. Version of joomla : 3.3.6
When I try to access the component, I have this error:
"Invalid backend response.
Data is empty."
Thanks for your answer

**Comment by asika32764** [comment]
This might caused by many reasons. Could you open Chrome Development Tools and switch to `Network` tab, then refresh page. Check what is the Ajax returned and get a screen shot for me.

**Comment by asika32764** [comment]
No update of this issue, close first. Feel free to re-open it.
