### ISSUE TITLE
remoteimage not working on joomla 3.4

### ISSUE THREAD

**Issue by benjoman** [asikart/remoteimage#40]
this is what i get when i trying to enter component or images and link tab
 500 Library path /libraries/framework cannot be found.

**Comment by asika32764** [comment]
Please see: https://github.com/asikart/remoteimage/issues/38

Just create an empty folder at `/libraries/framework`, then component will work.

We'll fix this error in about April

**Comment by benjoman** [comment]
thanks, works for me.

**Comment by asika32764** [comment]
Should work in [2.0.4](https://github.com/asikart/remoteimage/releases/tag/2.0.4)
