### ISSUE TITLE
cant rename names of folders and files

### ISSUE THREAD

**Issue by benjoman** [asikart/remoteimage#41]
Hello,
i cant change names of folders and files...
even on right click menu...
the rename button on the top menu is not "lighten" when you click on the file or folder...

using joomla 3.4.0

![screenshot 2015-03-04 13 19 28](https://cloud.githubusercontent.com/assets/11272293/6482693/5bd4a8d0-c271-11e4-908f-c76908731947.png)

**Comment by asika32764** [comment]
Please close "Safe Mode" in component options.
