### ISSUE TITLE
Error in Joomla 3.4.1 rc2

### ISSUE THREAD

**Issue by Gerlof** [asikart/remoteimage#43]
After installing RemoteImage and selecting Components > RemoteImage from the admin menu, this error message is shown:

An error has occurred.
 0 Key JLanguage has not been registered with the container.

**Comment by asika32764** [comment]
Should be fixed in [2.0.5](https://github.com/asikart/remoteimage/releases/tag/2.0.5)

**Comment by Gerlof** [comment]
Component works again. Thanks for fixing!
Regards, Gerlof

**Comment by SemaphoreOxalis** [comment]
Fixed Thanks
