### ISSUE TITLE
No longer installable...

### ISSUE THREAD

**Issue by webjive** [asikart/remoteimage#44]
Looks like the package is no longer installable on Joomla 3.4. 

Error
No file selected.

Unable to find install package

**Comment by asika32764** [comment]
It caused by a Joomla 3.4 bug, see: https://docs.joomla.org/J3.x:Extension_won't_install/en

To solve this problem, just uncompress the install package and recompress it.

**Comment by webjive** [comment]
Thanks!

**Comment by webjive** [comment]
Just ran into another error installing uncompressed. 
![screen shot 2015-03-20 at 12 49 22 pm](https://cloud.githubusercontent.com/assets/286935/6757517/ae6d2c26-ceff-11e4-9609-b690790859a5.png)

**Comment by webjive** [comment]
Got it figured out. Yummy FTP didn't upload that hidden file.

**Comment by asika32764** [comment]
Issue resolved, close.
