### ISSUE TITLE
Key JLanguage has not been registered with the container. bug

### ISSUE THREAD

**Issue by benjoman** [asikart/remoteimage#45]
hello,
i just upgrade to joomla 3.4.1 and i get this bug
Key JLanguage has not been registered with the container.
![screenshot 2015-03-22 10 50 17](https://cloud.githubusercontent.com/assets/11272293/6768678/e85d8500-d082-11e4-9f40-949d184bb6ca.png)

**Comment by asika32764** [comment]
I think it is a B/C break of Joomla 3.4.1

Please wait us for the update.

**Comment by SemaphoreOxalis** [comment]
Same here of course

**Comment by BettonDesign** [comment]
Any news on an update for this?

**Comment by mignolo1977** [comment]
Try to delete Remote Image component ;-)

**Comment by SemaphoreOxalis** [comment]
And re-install ? It worked for you ?

**Comment by BettonDesign** [comment]
Re-installing version 2.0.4 doesn't work for me. I still get the same error.

**Comment by asika32764** [comment]
Sorry, I'm moving house recently and I don't have computer to update
extensions.

This is a B/C break of Joomla when 3.4 update to 3.4.1, I think we should
wait for Joomla 3.4.2 to check that there are no more B/C breaks.

I'll release the fixes when I'm able to use computer.

2015-03-30 16:48 GMT+08:00 BettonDesign <notifications@github.com>:

> Re-installing version 2.0.4 doesn't work for me. I still get the same
> error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/remoteimage/issues/45#issuecomment-87594423>.
>



-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by mignolo1977** [comment]
Doesn't work for me also...

**Comment by ehsanasgari** [comment]
I get the same error for "userxtd" plugin..

**Comment by micker** [comment]
please update github ....error already exist

**Comment by epson950** [comment]
when you correct this error?

**Comment by farhadst** [comment]
i get the same error after update joomla to 3.4.1

**Comment by asika32764** [comment]
Please install new Windwalker library to fix this issue.
https://github.com/ventoviro/windwalker-joomla-rad/releases/download/2.0.10/windwalker-rad-2.0.10.zip

We'll release a new version of RemoteImage soon.

**Comment by asika32764** [comment]
Should be fixed in [2.0.5](https://github.com/asikart/remoteimage/releases/tag/2.0.5)
