### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by BettonDesign** [asikart/remoteimage#46]
Joomla 3.3.6
Remoteimage 2.0.4

Hi
I am getting the following PHP error for a website I administer:

Fatal error: Call to undefined method Composer\Autoload\ClassLoader::setPsr4() in /home/sites/mywebsite.com/public_html/libraries/windwalker/vendor/composer/autoload_real.php on line 33

**Comment by asika32764** [comment]
This is a bug of Akeeba GEO plugin, please update Akeeba to newest version or just remove GEO plugin.

**Comment by BettonDesign** [comment]
Thank you for your help :)
