### ISSUE TITLE
Remoteimage 2.0.5 bugs with Joomla 3.4.1

### ISSUE THREAD

**Issue by radik10** [asikart/remoteimage#53]
I have found some bugs:

-    remoteimage-2.0.5 is not possible to unzip on windows - there (...\libraries\windwalker\bundles\GeneratorBundle\Template\component\default\administrator\) are wrong file names "{{extension.name.lower}}.php" and "{{extension.name.lower}}.xml" - should be some normal name like "extension.name.lower.php" same files are after install on server or localhost. Same is with ini files (en-GB)

- remoteimage-2.0.5 is not compatible on localhost site (joomla 3.4.1) - after installation, and clicking "articles / media manager" there is error "500 Library path \libraries/framework cannot be found. " this problem is only with joomla 3.4.1 on localhost, on live server is your component loaded as media manager. remotemedia 2.0.5 on localhost has not this problem with Joomla 3.3.6

Here are not bugs, but ideas for improvements
-  upload images - please add possibility to define (extra) size of image during upload (in settings you can define resize parameter but many times you need different image sizes - now you have to manualy resize images after upload)

-    rename files during upload (letters - characters replacement): if you have photo named for example "Banícky dôm na Moyzečovej ulici.JPG" after upload on server it will be renamed as "banicky-dom-na-moyzecovej-ulici.jpg" so some special letters will be renamed as K2 has table rename letters table in settings...

**Comment by asika32764** [comment]
> remoteimage-2.0.5 is not possible to unzip on windows

What tool do you use on unzip Remoteimage? I can unzip it on both Windows and unix system.

The `{{extension.name.lower}}.php` is template file.

> remoteimage-2.0.5 is not compatible on localhost site (joomla 3.4.1) 

This should be fixed in 2.0.5. If it still not work on your computer, you can copy the Newest Windwalker to `libraries` to fix this bug.

https://github.com/ventoviro/windwalker-joomla-rad/releases

About your ideas, it is good idea, but I need some time to check is it possible implement in Remoteimage since this extensions is build on elFinder, it's depends on what elFinder support.

**Comment by radik10** [comment]
HiI have try to unzip "remoteimage-2.0.5" by ZipGenius, there was problem, but with 7-zip it was un-zipped without error message.
Unziping "windwalker-rad-2.0.10.zip" to libraries\windwalker has solved my problem with "error 500" - now it is possible to open remoteimage205 with joomla341 on localhost. So please add content of "windwalker-rad-2.0.10.zip" to latest installation file of remoteimage.
Best regards,R.J.
 


     On Wednesday, May 13, 2015 8:48 AM, Simon Asika <notifications@github.com> wrote:
   

 
remoteimage-2.0.5 is not possible to unzip on windows
What tool do you use on unzip Remoteimage? I can unzip it on both Windows and unix system.The {{extension.name.lower}}.php is template file.
remoteimage-2.0.5 is not compatible on localhost site (joomla 3.4.1) 
This should be fixed in 2.0.5. If it still not work on your computer, you can copy the Newest Windwalker to libraries to fix this bug.https://github.com/ventoviro/windwalker-joomla-rad/releasesAbout your ideas, it is good idea, but I need some time to check is it possible implement in Remoteimage since this extensions is build on elFinder, it's depends on what elFinder support.—
Reply to this email directly or view it on GitHub.   

   
     On Wednesday, May 13, 2015 8:48 AM, Simon Asika <notifications@github.com> wrote:
   

 
remoteimage-2.0.5 is not possible to unzip on windows
What tool do you use on unzip Remoteimage? I can unzip it on both Windows and unix system.The {{extension.name.lower}}.php is template file.
remoteimage-2.0.5 is not compatible on localhost site (joomla 3.4.1) 
This should be fixed in 2.0.5. If it still not work on your computer, you can copy the Newest Windwalker to libraries to fix this bug.https://github.com/ventoviro/windwalker-joomla-rad/releasesAbout your ideas, it is good idea, but I need some time to check is it possible implement in Remoteimage since this extensions is build on elFinder, it's depends on what elFinder support.—

**Comment by asika32764** [comment]
Windwalker RAD 2.0.10 has already included in ARI 2.0.5, I guess it may be some problem when you installing ARI 2.0.5. But it works fine for me on my server and computer.

Since this issue has resolved, I close this issue.
