### ISSUE TITLE
What is hiddeninput.exe doing inside this component?

### ISSUE THREAD

**Issue by jonnypixel** [asikart/remoteimage#54]
I was scanning for .exe files and found this. Please tell me what this is?

libraries/windwalker/vendor/asika/joomla-console/Joomla/Console/bin/hiddeninput.exe

**Comment by asika32764** [comment]
This file dose not work in ARI, it is part of Windwalker framework Console package.

The `hiddeninput.exe` is use to hide password when user typing in Windows CLI interface.

See: https://github.com/Seldaek/hidden-input

**Comment by jonnypixel** [comment]
Hi Thanks,

I was curious about it.

Can i ask you please, why do i need so much of windwalker in order to 
use remoteimage ( elfinder ) it appears to be massive and dosent look 
like it is all being used for remote image only?

Can i remove windwalker and still keep using remoteimage?

Cheers
John

**Comment by asika32764** [comment]
No, because we use Windwalker to develop many of our extensions to make sure we can maintain so many extensions. The ARI main structure is built on Windwlaker, if you remove it, ARI will not work anymore.

But you can remove hiddeninput.exe, if you just want to use RemoteImage.

**Comment by jonnypixel** [comment]
Thank you. and Thank you for integrating such an amazing media manager within joomla. Can i ask if there is a way to integrate the right click and edit with pixlr - i think that was once available in the actual elfinder. Is there some way of adding a third party picture editor within the interface? And another question. Is there an easy way we can tell the joomla user that if  they delete that photo or move that photo that it will affect the following articles?

**Comment by asika32764** [comment]
For first question, pixlr is available on old version of ARI, but I don't know why it disappeared in current version which I upgraded elFinder. The elFinder is still no stable release so it's hard to choose a correct version to use. Maybe it has to wait for my next update of ARI to use the newest elFinder.

For second question, I think it is up to the site builder. Maybe add some custom message in admin template.

**Comment by jonnypixel** [comment]
Ok cool, thank you. Can i install old version of ARI inside new joomla?

**Comment by asika32764** [comment]
Actually, I don't know which version has the pixir function. Maybe the very
old version for Joomla 2.5.

elFinder has long time not update in ARI, since it not stable, every new
version has some difference may break ARI.

2015-05-25 14:39 GMT+08:00 jonnypixel <notifications@github.com>:

> Ok cool, thank you. Can i install old version of ARI inside new joomla?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/remoteimage/issues/54#issuecomment-105140767>.
>



-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by jonnypixel** [comment]
Ok no worries, thank you
