### ISSUE TITLE
folder is locked and can not be renamed, moved or removed

### ISSUE THREAD

**Issue by benjoman** [asikart/remoteimage#55]
hello, 
i get this error ""images/musica/gallery/untitled folder/.unitegallery_thumbs" is locked and can not be renamed, moved or removed." 
when i'm trying to delete folder.. "safe mode is disable" so what can do it ? i'm super user ?

please advice what to check ?

remote image 2.0.5
joomla 3.4.1
![screenshot 2015-06-28 12 07 11](https://cloud.githubusercontent.com/assets/11272293/8395777/3fcc0caa-1d8e-11e5-9565-813fbe7076e1.png)

**Comment by asika32764** [comment]
Try disable safe mode in options.

**Comment by benjoman** [comment]
hello,
"safe mode is already disable" its not working... 
please advice, what else can i check ?

**Comment by asika32764** [comment]
Then I think maybe it is the filesystem permissions reason.

Can you check that your Apache can modify your files on host?

**Comment by asika32764** [comment]
All folder are locked or only ".unitegallery_thumbs" folder?

**Comment by benjoman** [comment]
i looked at my hosting panel file browser, from there i've been able to delete the folder, new folder i create from the remote image gets "755" permission number ? is it ok ?
i also tried to delete folder from JCE editor and its gives me this error ?
"Fatal error: Call to undefined method WFJoomlaFileSystem::countFolders() in /home/artmusic/domains/art-music.co.il/public_html/components/com_jce/editor/extensions/filesystem/joomla.php on line 366" 
it also cant delete folders from joomla ?

**Comment by asika32764** [comment]
I am not sure what is the reason, but use cpanel to delete it is a correct way, maybe this folder has some system permission. The 755 permission of now folder is ok.

Since this issue has resolved, I will close it.
