### ISSUE TITLE
Latest uploads

### ISSUE THREAD

**Issue by Kaszika** [asikart/remoteimage#57]
That modul was created by you is great!
But I would like to ask you how can I adjust the capital sequence of the file names of the uploaded pictures? I would like to put the latest uploads to the top of the list.

Thanks for your help in advance!

Best Regards,

**Comment by asika32764** [comment]
Unfortunately this is impossible in current [elFinder](http://elfinder.org/)

RemoteImage use this as image finder, and it seems elFinder dose not support ordering by file time.

**Comment by Kaszika** [comment]
Thanks for your comment! I make my question more detailed to let you understand my target:
As you can see on the link shown here under you can adjust the sequence of the "Modified" column by the "Date of upload" feature http://elfinder.org/#elf_l2_dW50aXRsZWQgZm9sZGVy
Can you please let me know how can I adjust the sequence like this?
Thanks in advance!
