### ISSUE TITLE
Error selected an image in other composant 

### ISSUE THREAD

**Issue by manudss** [asikart/remoteimage#7]
When I select the image, in smart slider 2 component, like this :  
![animation 1](https://cloud.githubusercontent.com/assets/1046806/2717987/882aab36-c548-11e3-8063-028253bb6875.gif)

After selected the image, I have this : 

![image](https://cloud.githubusercontent.com/assets/1046806/2718012/d0758604-c548-11e3-890a-916ec13111d2.png)

It give a wrong url : juste www.nomdusite.com/undefined. 

Do you have an idea how to correct that ? 

Many thanks in advence. 

Regards, 

Emmanuel

**Comment by asika32764** [comment]
Sorry for lately reply.

We don't have Smart Slider 2 to test, maybe you can disable the remoteimage plugin to fallback to Joomla default media manager. I think that will works.

Thank you

**Comment by asika32764** [comment]
There's no update of this issue, closed.
