### ISSUE TITLE
to change height of a main window

### ISSUE THREAD

**Issue by epson950** [asikart/remoteimage#84]
to change height of a main window that buttons of management were available
![image025343_19122017](https://user-images.githubusercontent.com/11770015/34133885-5ec99ae8-e468-11e7-9d74-fb8f264df12e.jpg)
![image025419_19122017](https://user-images.githubusercontent.com/11770015/34133889-6526d504-e468-11e7-9119-62bfb981d592.jpg)

**Comment by asika32764** [comment]
Did you open Remoteimage by built-in media button or Remoteimage button?

**Comment by epson950** [comment]
built-in media button (joomla article image)

**Comment by asika32764** [comment]
Consider use Remoteimage's button, Remoteimage cannot override Joomla built-in button height.
