### ISSUE TITLE
Add Selected Sorting

### ISSUE THREAD

**Issue by farhadst** [asikart/remoteimage#85]
Hi
Now in the latest version of remoteimage, sorting is by name
and in the new version of [elifinder ](https://github.com/Studio-42/elFinder) there is a possibility of sorting selectively (name, date, etc.).
I have replaced some files of remoteimage with the new version of elifider and added the sorting but may have bugs.
can u update the remoteimage with new version of elifinder for add new sections?

Thanks for your works and best image manager in joomla

**Comment by asika32764** [comment]
I'm afraid that this may be impossible in Joomla3 since elFinder uses newer jQuery UI version than Joomla has. So we are unable to upgrade elFinder for long time. Maybe this can be resolved after Joomla 4.
