### ISSUE TITLE
Wrong version in installed version after update of Windwalker Framework

### ISSUE THREAD

**Issue by ribo72** [asikart/remoteimage#89]
Hello, there is an update in Windwalker Framework and it show 4.1.16 Installed and 4.1.17 Available . When you install the update in joomla update for extensions after it show 2.1.18 Installed and 4.1.17 Available, so every time you update it show that it needs update. I also opened issue here https://github.com/ventoviro/windwalker/issues/514 but i dont know where i should open exactly the issue for this framework.

**Comment by greenkey-m** [comment]
Yes, i have a some problem. There was installed version 4 (previous), but now joomla show 2 version. I look to the library, and its really 2 version.
windwalker.xml - <version>2.1.18</version>

**Comment by greenkey-m** [comment]
And its not updating now through joomla updating system.

**Comment by robynlingen** [comment]
I can confirm this on three of my websites, and with each site, RemoteImage breaks with the error:

Invalid backend response. Data is not JSON.

I've stopped updating, but sometimes my clients update and then we're stuck. Any ideas on how to fix this? Thanks in advance!

**Comment by greenlizzard24** [comment]
This is happening on all my sites as well, any updates available as yet?

**Comment by asika32764** [comment]
Fixed
