### ISSUE TITLE
Error to connect Backend

### ISSUE THREAD

**Issue by djdlife** [asikart/remoteimage#90]
Hello

We get a Error, when we upload a image. This happen sometimes, not everytime. How can we solve this?
![server](https://user-images.githubusercontent.com/43954126/46602725-42b6b780-caf1-11e8-8520-fde79b866de9.jpg)

**Comment by robynlingen** [comment]
I can confirm this on three of my sites that use Remote Image. It happens even with small files and images.

**Comment by djdlife** [comment]
> I can confirm this on three of my sites that use Remote Image. It happens even with small files and images. We do not have FTP turned on, but that has never been an issue before.
> 
> I should also mention that this is with the Joomla 3.8.13 update.

What I find out. In the log we have seen, that the system try acces to the folder when we get this error: administrator/images

This is strange

**Comment by robynlingen** [comment]
In case this is still an issue for you, I was able to fix the json error by editing this file

/home/cityofea/public_html/administrator/components/com_remoteimage/src/Remoteimage/Component/RemoteimageComponent.php

commenting out this line 58:

// include_once JPATH_ADMINISTRATOR . '/includes/toolbar.php';

Everything working again!

**Comment by asika32764** [comment]
Please try 2.0.12
http://asikart.co/downloads/remoteimage.html
