### ISSUE TITLE
Errors after update joomla 3.9

### ISSUE THREAD

**Issue by pklinke** [asikart/remoteimage#92]
After update to joomla 3.9 I have this errors:

Warning: include_once(/home/www/fib.custsrv.de/administrator/includes/toolbar.php): failed to open stream: No such file or directory in /home/www/pathtomyfolder/administrator/components/com_remoteimage/src/Remoteimage/Component/RemoteimageComponent.php on line 58

Warning: include_once(): Failed opening '/home/www/fib.custsrv.de/administrator/includes/toolbar.php' for inclusion (include_path='.:/usr/share/php') in /home/www/pathtomyfolder/administrator/components/com_remoteimage/src/Remoteimage/Component/RemoteimageComponent.php on line 58

and
Ungültige Backend Antwort.
Daten nicht im JSON Format.

toolbar.php isnt't there. Wehen I copy a toolpar.php from another installation, only the backend error is still there.

Another installation with joomla 3.9 works well.

**Comment by asika32764** [comment]
Please try 2.0.12
http://asikart.co/downloads/remoteimage.html

**Comment by pklinke** [comment]
The issue still exists.

**Comment by asika32764** [comment]
Is the error message still show as: `Warning: include_once(/home/www/fib.custsrv.de/administrator/includes/toolbar.php): failed to open stream`?

**Comment by raramuridesign** [comment]
Also getting the same error
